# coding: utf-8

# flake8: noqa

"""
    Unstructured Pipeline API

    At Unstructured, we're on a mission to give organizations access to all of their data. We know the world runs on documents—from research reports and memos, to quarterly filings and plans of action, documents are the unit of information that companies depend on. And yet, 80% of this information is trapped in inaccessible formats, and businesses have long struggled to unlock this data, leading to information silos, inefficient decision-making, and repetitive work. Until now.  Unstructured captures this unstructured data wherever it lives and transforms it into AI-friendly JSON files for companies who are eager to fold AI into their business.

    The version of the OpenAPI document: 0.0.1
    Generated by: https://konfigthis.com
"""

__version__ = "0.0.1"

# import ApiClient
from unstructured_python_sdk.api_client import ApiClient

# import Configuration
from unstructured_python_sdk.configuration import Configuration

# import exceptions
from unstructured_python_sdk.exceptions import OpenApiException
from unstructured_python_sdk.exceptions import ApiAttributeError
from unstructured_python_sdk.exceptions import ApiTypeError
from unstructured_python_sdk.exceptions import ApiValueError
from unstructured_python_sdk.exceptions import ApiKeyError
from unstructured_python_sdk.exceptions import ApiException

from unstructured_python_sdk.client import Unstructured
