# coding: utf-8
"""
    Unstructured Pipeline API

    At Unstructured, we're on a mission to give organizations access to all of their data. We know the world runs on documents—from research reports and memos, to quarterly filings and plans of action, documents are the unit of information that companies depend on. And yet, 80% of this information is trapped in inaccessible formats, and businesses have long struggled to unlock this data, leading to information silos, inefficient decision-making, and repetitive work. Until now.  Unstructured captures this unstructured data wherever it lives and transforms it into AI-friendly JSON files for companies who are eager to fold AI into their business.

    The version of the OpenAPI document: 0.0.1
    Generated by: https://konfigthis.com
"""

import typing
import inspect
from datetime import date, datetime
from unstructured_python_sdk.client_custom import ClientCustom
from unstructured_python_sdk.configuration import Configuration
from unstructured_python_sdk.api_client import ApiClient
from unstructured_python_sdk.type_util import copy_signature
from unstructured_python_sdk.apis.tags.general_api import GeneralApi



class Unstructured(ClientCustom):

    def __init__(self, configuration: typing.Union[Configuration, None] = None, **kwargs):
        super().__init__(configuration, **kwargs)
        if (len(kwargs) > 0):
            configuration = Configuration(**kwargs)
        if (configuration is None):
            raise Exception("configuration is required")
        api_client = ApiClient(configuration)
        self.general: GeneralApi = GeneralApi(api_client)
