# coding: utf-8

"""
    Unstructured Pipeline API

    At Unstructured, we're on a mission to give organizations access to all of their data. We know the world runs on documents—from research reports and memos, to quarterly filings and plans of action, documents are the unit of information that companies depend on. And yet, 80% of this information is trapped in inaccessible formats, and businesses have long struggled to unlock this data, leading to information silos, inefficient decision-making, and repetitive work. Until now.  Unstructured captures this unstructured data wherever it lives and transforms it into AI-friendly JSON files for companies who are eager to fold AI into their business.

    The version of the OpenAPI document: 0.0.1
    Generated by: https://konfigthis.com
"""

import unittest

import os
from pprint import pprint
from unstructured_python_sdk import Unstructured

class TestSimple(unittest.TestCase):
    def setUp(self):
        pass

    def test_client(self):
        unstructured = Unstructured(
        
                        api_key_auth = 'YOUR_API_KEY',
        )
        self.assertIsNotNone(unstructured)

    def tearDown(self):
        pass


if __name__ == "__main__":
    unittest.main()
