# coding: utf-8

"""
    Unstructured Pipeline API

    At Unstructured, we're on a mission to give organizations access to all of their data. We know the world runs on documents—from research reports and memos, to quarterly filings and plans of action, documents are the unit of information that companies depend on. And yet, 80% of this information is trapped in inaccessible formats, and businesses have long struggled to unlock this data, leading to information silos, inefficient decision-making, and repetitive work. Until now.  Unstructured captures this unstructured data wherever it lives and transforms it into AI-friendly JSON files for companies who are eager to fold AI into their business.

    The version of the OpenAPI document: 0.0.1
    Generated by: https://konfigthis.com
"""

from unstructured_python_sdk.paths.general_v0_general.post import CreatePipeline
from unstructured_python_sdk.apis.tags.general_api_raw import GeneralApiRaw


class GeneralApi(
    CreatePipeline,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: GeneralApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = GeneralApiRaw(api_client)
